# Generated by Django 3.1.3 on 2020-11-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='cost_of_revenue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default='stock', max_length=200),
        ),
        migrations.AddField(
            model_name='stock',
            name='pe',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='total_revenue',
            field=models.IntegerField(default=0),
        ),
    ]
