# Generated by Django 3.1.3 on 2020-11-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20201120_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='pe',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
