# Generated by Django 3.1.3 on 2020-11-25 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20201120_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='cost_of_revenue',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='total_revenue',
        ),
    ]
