# Generated by Django 3.1.3 on 2020-11-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20201125_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='eps',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='leverage_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='pe',
            field=models.FloatField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='roce',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
