# Generated by Django 3.1.3 on 2020-11-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_auto_20201125_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default='Stock', max_length=200),
        ),
    ]
